CUDAROOT='n:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0'
export KALDI_HOME=/home/u1273400/kaldi
export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT
